### ISSUE TITLE
Vite and Twig?

### ISSUE THREAD

**Issue by dannystarkDE** [wearejust/kirby-twig#2]
Does anyone use the plugin in combination with Vite?

I use the basic installation of https://github.com/arnoson/kirby-vite-basic-kit. However, all I get from Twig is the message "Unknown "vite" function. Did you mean "site"?".

I would appreciate any help.

**Comment by andrepimpao** [comment]
You need to expose the `vite` function to be available in your templates https://github.com/wearejust/kirby-twig/blob/master/doc/functions.md#exposing-a-function.

Something like:
```php
// config/config.php

return [
  'wearejust.twig.env.functions' => [
    'vite' => 'vite'
  ]
];
```

And in your template:
```twig
{{ vite().js('path/to/app.js')|raw }}
```

Note that I added `|raw` at the end because Twig escapes strings by default.

Hope it helps!

**Comment by dannystarkDE** [comment]
Thank you very much. That works!
